name: Deploy MyHireShield

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Project folder mein jana
            cd /var/www/myhireshield
            
            # 2. GitHub se naya code khinchna
            git pull origin main
            
            # 3. Backend Setup
            cd server
            npm install
            pm2 restart hireshield-api || pm2 start server.js --name "hireshield-api"
            
            # 4. Frontend Setup (Naya Build banana)
            cd ../client
            npm install
            chmod +x node_modules/.bin/vite
            npm run build
            
            # 5. Permissions (Taki Nginx files read kar sake)
            sudo chown -R www-data:www-data /var/www/myhireshield
            sudo chmod -R 755 /var/www/myhireshield