name: Auto Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 62.72.57.197
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/myhireshield/htdocs/myhireshield.com
            git config --global --add safe.directory /home/myhireshield/htdocs/myhireshield.com
            git pull origin main
            cd client && npm install && npm run build
            rm -rf ../assets
            cp -r dist/* ../
            cd ../backend && npm install
            pm2 restart hireshield-api
            chown -R myhireshield:myhireshield /home/myhireshield/htdocs/myhireshield.com
            systemctl reload nginx